Repository boostcampwm-2021/WEB13-JDevBook, pull requests merged in 2021-12, with the labels that each got.

#201 [Day27] Cypress 설치 & 코드 리팩토링 & 로그인페이지 CSS 반응형 구현
  client/cypress.json
  client/cypress/fixtures/example.json
  client/cypress/integration/LoginPageTest.js
  client/cypress/plugins/index.js
  client/cypress/support/commands.js
  client/cypress/support/index.js
  client/package-lock.json
  client/package.json
  client/src/Router.tsx
  client/src/components/GroupPage/GroupChat/ChatInput/index.tsx
  client/src/components/GroupPage/GroupChat/ChatList/index.tsx
  client/src/components/GroupPage/GroupChat/ChatTitle/index.tsx
  client/src/components/GroupPage/GroupChat/CurrentUserContainer/index.tsx
  client/src/components/GroupPage/GroupChat/CurrentUserTitle/index.tsx
  client/src/components/GroupPage/GroupChat/SubmitBtn/index.tsx
  client/src/components/GroupPage/GroupChat/index.tsx
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/HomePage/Post/Comment/CommentInputBox/index.tsx
  client/src/components/HomePage/Post/Comment/CommentListView/index.tsx
  client/src/components/HomePage/Post/Comment/index.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/LoginPage/Footer/index.tsx
  client/src/components/LoginPage/Greeter/index.tsx
  client/src/components/LoginPage/LoginBox/index.tsx
  client/src/components/common/AlarmSideBar/AlarmListView/index.tsx
  client/src/components/common/AlarmSideBar/index.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/ChatSideBar/ChatInput/index.tsx
  client/src/components/common/ChatSideBar/ChatList/index.tsx
  client/src/components/common/ChatSideBar/ChatTitle/index.tsx
  client/src/components/common/ChatSideBar/CurrentUser/index.tsx
  client/src/components/common/ChatSideBar/CurrentUserTitle/index.tsx
  client/src/components/common/ChatSideBar/SubmitBtn/index.tsx
  client/src/components/common/ChatSideBar/index.tsx
  client/src/pages/LoginPage.tsx
Labels: Frontend 🖥, Test 🧪

#203 [Day27] 로그인 페이지 로딩 해결 및 리팩토링 등
  README.md
  client/src/Router.tsx
  client/src/pages/IsLoginPage.tsx
  client/src/pages/LoadingWhitePage.tsx
  client/src/pages/index.tsx
  server/src/app.ts
  server/src/routes/api.ts
  server/src/routes/middleware/api/comments.ts
  server/src/routes/middleware/api/groups.ts
  server/src/routes/middleware/api/image.ts
  server/src/routes/middleware/api/index.ts
  server/src/routes/middleware/api/isLogin.ts
  server/src/routes/middleware/api/likes.ts
  server/src/routes/middleware/api/posts.ts
  server/src/routes/middleware/api/problems.ts
  server/src/routes/middleware/api/profile.ts
  server/src/routes/middleware/api/users.ts
  server/src/routes/middleware/oauth/index.ts
  server/src/routes/middleware/oauth/login.ts
  server/src/routes/middleware/oauth/logout.ts
  server/src/routes/oauth.ts
  server/src/service/objectStorage.ts
Labels: Frontend 🖥, Backend 💾, Bug :bug:

#204 [Day27] 알림 모달창 로직 변경 및 리팩토링
  client/package-lock.json
  client/src/App.tsx
  client/src/Router.tsx
  client/src/components/GroupPage/GroupNavBar/GroupNavigation.tsx
  client/src/components/GroupPage/InitGroupData/index.tsx
  client/src/components/GroupSelectPage/GroupSelectList/index.tsx
  client/src/components/GroupSelectPage/GroupSelectTitle.tsx
  client/src/components/common/AlertModal/index.tsx
  client/src/components/common/ChatSideBar/index.tsx
  client/src/components/common/InitTheme/index.tsx
  client/src/components/common/LeftSideBar/GroupSideBar/JoinedGroupCard.tsx
  client/src/components/common/LeftSideBar/GroupSideBar/index.tsx
  client/src/components/common/LeftSideBar/InfoSideBar/index.tsx
  client/src/components/common/LeftSideBar/index.tsx
  client/src/components/common/ProfilePhoto/index.tsx
  client/src/components/common/index.tsx
  client/src/hooks/useAlertModal.tsx
  client/src/recoil/store.ts
Labels: Frontend 🖥

#208 [Day28] 동일 브라운저 문제, 이미지 유효성, server/client 리팩토링 등
  client/src/Router.tsx
  client/src/api/fetch.ts
  client/src/api/fetch/comments.ts
  client/src/api/fetch/groups.ts
  client/src/api/fetch/image.ts
  client/src/api/fetch/index.ts
  client/src/api/fetch/like.ts
  client/src/api/fetch/login.ts
  client/src/api/fetch/logout.ts
  client/src/api/fetch/posts.ts
  client/src/api/fetch/problems.ts
  client/src/api/fetch/profile.ts
  client/src/api/fetch/users.ts
  client/src/components/GroupPage/GroupChat/index.tsx
  client/src/components/common/AlarmSideBar/index.tsx
  client/src/components/common/Gnb/index.tsx
  client/src/components/common/InitUserData.tsx
  server/src/app.ts
  server/src/routes/api.ts
  server/src/routes/middleware/api/comments.ts
  server/src/routes/middleware/api/isLogin.ts
  server/src/routes/middleware/api/posts.ts
  server/src/routes/middleware/api/profile.ts
  server/src/routes/middleware/api/users.ts
  server/src/routes/middleware/oauth/login.ts
  server/src/service/dbManager/alarm.ts
  server/src/service/dbManager/comment.ts
  server/src/service/dbManager/groupchat.ts
  server/src/service/dbManager/index.ts
  server/src/service/dbManager/init.ts
  server/src/service/dbManager/post.ts
  server/src/service/dbManager/search.ts
  server/src/service/dbManager/user.ts
  server/src/service/githubOauth.ts
  server/src/service/objectStorage.ts
  server/src/sockets/socketIO.ts
  server/src/types/customType.ts
  server/src/types/database.ts
  server/src/types/index.ts
  server/src/types/interface.ts
Labels: Frontend 🖥, Backend 💾

#207 [Day28] 무한 토글 버그 수정 & will-change 공부 & 리팩토링
  client/src/components/GroupPage/GroupChat/index.tsx
  client/src/components/common/AlarmSideBar/index.tsx
  client/src/components/common/ChatSideBar/index.tsx
  server/src/sockets/alarmSocket.ts
  server/src/sockets/chatSocket.ts
  server/src/sockets/commentSocket.ts
  server/src/sockets/groupChatSocket.ts
  server/src/sockets/postSocket.ts
  server/src/sockets/socketIO.ts
Labels: Frontend 🖥

#213 [Day29] 발견 버그 수정
  README.md
  client/src/components/common/AlarmSideBar/AlarmListView/index.tsx
  client/src/pages/IsLoginPage.tsx
  client/src/pages/LoadingWhitePage.tsx
Labels: Frontend 🖥

#214 [Day29] Main PR 2
  client/src/components/common/AlarmSideBar/AlarmListView/index.tsx
  client/src/pages/IsLoginPage.tsx
  client/src/pages/LoadingWhitePage.tsx
Labels: Main PR 👾

#215 [J6543-JDevBook] 6주차(최종2) 배포
  client/src/components/common/AlarmSideBar/AlarmListView/index.tsx
  client/src/pages/IsLoginPage.tsx
  client/src/pages/LoadingWhitePage.tsx
Labels: Release 🔥

#216 [리팩토링] 리렌더링 일부 개선
  client/src/api/fetch/posts.ts
  client/src/components/HomePage/Post/Header.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostList/index.tsx
  client/src/components/HomePage/PostWriter/index.tsx
  client/src/components/HomePage/PostWriterModal/AddContentsBar.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/ModalTitle.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/ProfilePage/PostList/index.tsx
  client/src/components/ProfilePage/ProfileBar/ProfileEdit.tsx
  client/src/components/ProfilePage/ProfileEditModal/index.tsx
  client/src/components/common/Gnb/UserCard.tsx
  client/src/components/common/Gnb/UserSearchBar.tsx
  client/src/components/common/Gnb/UserSearchModal.tsx
  client/src/components/common/ProfilePhoto/index.tsx
  client/src/hooks/useModalHandler.tsx
  client/src/hooks/useResetPostModal.tsx
  client/src/hooks/useResetProfile.tsx
  client/src/pages/GroupPage.tsx
  client/src/pages/GroupSelectPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/recoil/common/index.tsx
  client/src/types/common/index.tsx
Labels: Frontend 🖥

#217 [Day α] Main PR
  client/src/api/fetch/posts.ts
  client/src/components/HomePage/Post/Header.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostList/index.tsx
  client/src/components/HomePage/PostWriter/index.tsx
  client/src/components/HomePage/PostWriterModal/AddContentsBar.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/ModalTitle.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/ProfilePage/PostList/index.tsx
  client/src/components/ProfilePage/ProfileBar/ProfileEdit.tsx
  client/src/components/ProfilePage/ProfileEditModal/index.tsx
  client/src/components/common/Gnb/UserCard.tsx
  client/src/components/common/Gnb/UserSearchBar.tsx
  client/src/components/common/Gnb/UserSearchModal.tsx
  client/src/components/common/ProfilePhoto/index.tsx
  client/src/hooks/useModalHandler.tsx
  client/src/hooks/useResetPostModal.tsx
  client/src/hooks/useResetProfile.tsx
  client/src/pages/GroupPage.tsx
  client/src/pages/GroupSelectPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/recoil/common/index.tsx
  client/src/types/common/index.tsx
Labels: Main PR 👾

#218 [J6543-JDevBook] 6주차(최종3) 배포
  client/src/api/fetch/posts.ts
  client/src/components/HomePage/Post/Header.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostList/index.tsx
  client/src/components/HomePage/PostWriter/index.tsx
  client/src/components/HomePage/PostWriterModal/AddContentsBar.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/ModalTitle.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/ProfilePage/PostList/index.tsx
  client/src/components/ProfilePage/ProfileBar/ProfileEdit.tsx
  client/src/components/ProfilePage/ProfileEditModal/index.tsx
  client/src/components/common/Gnb/UserCard.tsx
  client/src/components/common/Gnb/UserSearchBar.tsx
  client/src/components/common/Gnb/UserSearchModal.tsx
  client/src/components/common/ProfilePhoto/index.tsx
  client/src/hooks/useModalHandler.tsx
  client/src/hooks/useResetPostModal.tsx
  client/src/hooks/useResetProfile.tsx
  client/src/pages/GroupPage.tsx
  client/src/pages/GroupSelectPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/recoil/common/index.tsx
  client/src/types/common/index.tsx
Labels: Release 🔥
