Repository boostcampwm-2021/WEB13-JDevBook, pull requests merged in 2021-11, with the labels that each got.

#47 [Day06] 로그인 페이지 Title Animation
  client/package-lock.json
  client/src/App.tsx
  client/src/pages/login/Greeter.tsx
  client/src/pages/login/LoginBox.tsx
  server/package-lock.json
Labels: Frontend 🖥

#49 [Day06] GNB 레이아웃 구성
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.css
  client/src/App.tsx
  client/src/Router.tsx
  client/src/components/AlertSideBar.tsx
  client/src/components/ChatSideBar.tsx
  client/src/components/Gnb.tsx
  client/src/components/GruopSideBar.tsx
  client/src/components/InfoSideBar.tsx
  client/src/components/SideBar.tsx
  client/src/components/index.tsx
  client/src/images/gnb-alarm.svg
  client/src/images/gnb-down-arrow.svg
  client/src/images/gnb-group-active.svg
  client/src/images/gnb-group.svg
  client/src/images/gnb-home-active.svg
  client/src/images/gnb-home.svg
  client/src/images/gnb-message.svg
  client/src/images/gnb-mypage.svg
  client/src/images/icon-search.svg
  client/src/images/main-logo.png
  client/src/index.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/index.tsx
Labels: Frontend 🖥

#50 [Day06] 공통 컴포넌트 파일 생성 및 Layout 작성
  client/src/App.tsx
  client/src/components/InfoSideBar.tsx
  client/src/components/ProfilePhoto.tsx
  client/src/components/index.tsx
  client/src/pages/HomePage.tsx
Labels: Frontend 🖥

#51 [Day07] Main PR
  .prettierrc
  README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.css
  client/src/App.tsx
  client/src/Router.tsx
  client/src/components/LoginPage/Greeter.tsx
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/common/AlertSideBar.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GruopSideBar.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/SideBar.tsx
  client/src/components/index.tsx
  client/src/images/githubLogo.png
  client/src/images/gnb-alarm.svg
  client/src/images/gnb-down-arrow.svg
  client/src/images/gnb-group-active.svg
  client/src/images/gnb-group.svg
  client/src/images/gnb-home-active.svg
  client/src/images/gnb-home.svg
  client/src/images/gnb-message.svg
  client/src/images/gnb-mypage.svg
  client/src/images/icon-search.svg
  client/src/images/main-logo.png
  client/src/index.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/index.tsx
  server/.gitignore
  server/package-lock.json
  server/src/app.ts
  server/src/routes/index.ts
  server/src/routes/oauth.ts
  server/src/service/githubOauth.ts
Labels: Main PR

#59 [Day07] 로그인, 환경변수, DB 구축시도
  client/.gitignore
  client/package.json
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/index.tsx
  client/src/pages/LoginPage.tsx
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/routes/index.ts
  server/src/routes/oauth.ts
  server/src/sequelize/models/index.ts
  server/src/sequelize/models/tb-chat.ts
  server/src/sequelize/models/tb-users.ts
  server/src/service/githubOauth.ts
  server/tsconfig.json
Labels: Backend 💾, Setting 🛠

#58 [Day07] GNB, 사용자 검색 모달 UI 구현 및 페이지 라우팅
  client/package-lock.json
  client/package.json
  client/src/Router.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/UserSearch.tsx
  client/src/components/index.tsx
  client/src/images/profile-default.png
  client/src/index.tsx
  client/src/pages/GroupPage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/pages/index.tsx
  client/src/recoil/modal.ts
Labels: Frontend 🖥

#57 [Day07] InfoSideBar, GroupSideBar UI 구현 및 페이지 이동 구현
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/images/default-profile.jpg
  client/tsconfig.json
Labels: Frontend 🖥

#54 [Day07] Login Page UI 작업 & Main(Home) Page 우측 GNB 토글 로직 작업
  client/package-lock.json
  client/package.json
  client/src/components/LoginPage/Footer.tsx
  client/src/components/LoginPage/Greeter.tsx
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/Gnb.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/LoginPage.tsx
Labels: Frontend 🖥

#60 [Day08] Main PR
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/Router.tsx
  client/src/components/LoginPage/Footer.tsx
  client/src/components/LoginPage/Greeter.tsx
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar.tsx
  client/src/components/common/GruopSideBar.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/UserSearch.tsx
  client/src/components/index.tsx
  client/src/images/default-profile.jpg
  client/src/images/profile-default.png
  client/src/index.tsx
  client/src/pages/GroupPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/pages/index.tsx
  client/src/recoil/modal.ts
  client/tsconfig.json
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/routes/index.ts
  server/src/routes/oauth.ts
  server/src/sequelize/models/index.ts
  server/src/sequelize/models/tb-chat.ts
  server/src/sequelize/models/tb-users.ts
  server/src/service/githubOauth.ts
  server/tsconfig.json
Labels: Main PR 👾

#61 [Day08] 클라이언트와 서버 소켓 연결 & Recoil 상태 관리로 변경
  client/package-lock.json
  client/package.json
  client/src/components/LoginPage/Greeter.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/Socket.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/LoginPage.tsx
  client/src/recoil/modal.ts
  client/src/utils/types.tsx
  server/package-lock.json
  server/package.json
  server/src/app.ts
Labels: Frontend 🖥, Backend 💾

#62 [Day08] 사용자 검색 클라이언트 데이터 시뮬레이션, 검색 모달 애니메이션 적용
  client/package-lock.json
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/UserCard.tsx
  client/src/components/common/UserSearch.tsx
  client/src/components/index.tsx
  client/src/pages/LoginPage.tsx
Labels: Frontend 🖥

#63 [Day08] 로그인-홈화면 연결 및 DB 구축 및 연동
  README.md
  client/public/index.html
  client/src/api/fetch.ts
  client/src/components/LoginPage/Footer.tsx
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/images/githubLogo.png
  client/src/pages/LoginPage.tsx
  client/src/recoil/modal.ts
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/models/index.ts
  server/src/models/tables/Alarm.ts
  server/src/models/tables/Chat.ts
  server/src/models/tables/Comment.ts
  server/src/models/tables/Group.ts
  server/src/models/tables/GroupChat.ts
  server/src/models/tables/Like.ts
  server/src/models/tables/Post.ts
  server/src/models/tables/Problem.ts
  server/src/models/tables/User.ts
  server/src/models/tables/UserGroup.ts
  server/src/models/tables/UserProblem.ts
  server/src/routes/api.ts
  server/src/routes/oauth.ts
  server/src/sequelize/models/index.ts
  server/src/sequelize/models/tb-chat.ts
  server/src/sequelize/models/tb-users.ts
  server/src/service/dbManager.ts
  server/src/service/githubOauth.ts
  server/src/service/interface.ts
Labels: Frontend 🖥, Backend 💾, Setting 🛠

#64 [Day08] 개인정보 사이드바, 가입 그룹 사이드바에 데이터에 따른 로직 구현
  client/public/index.html
  client/src/components/common/GroupSideBar.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/index.css
Labels: Frontend 🖥

#65 [Day08] Main PR
  README.md
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/api/fetch.ts
  client/src/components/LoginPage/Footer.tsx
  client/src/components/LoginPage/Greeter.tsx
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/Socket.tsx
  client/src/components/common/UserCard.tsx
  client/src/components/common/UserSearch.tsx
  client/src/components/index.tsx
  client/src/images/githubLogo.png
  client/src/index.css
  client/src/pages/HomePage.tsx
  client/src/pages/LoginPage.tsx
  client/src/recoil/modal.ts
  client/src/utils/types.tsx
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/models/index.ts
  server/src/models/tables/Alarm.ts
  server/src/models/tables/Chat.ts
  server/src/models/tables/Comment.ts
  server/src/models/tables/Group.ts
  server/src/models/tables/GroupChat.ts
  server/src/models/tables/Like.ts
  server/src/models/tables/Post.ts
  server/src/models/tables/Problem.ts
  server/src/models/tables/User.ts
  server/src/models/tables/UserGroup.ts
  server/src/models/tables/UserProblem.ts
  server/src/routes/api.ts
  server/src/routes/oauth.ts
  server/src/sequelize/models/index.ts
  server/src/sequelize/models/tb-chat.ts
  server/src/sequelize/models/tb-users.ts
  server/src/service/dbManager.ts
  server/src/service/githubOauth.ts
  server/src/service/interface.ts
Labels: Main PR 👾

#68 [Day09] logout api 및 1대1 채팅 구현
  client/src/api/fetch.ts
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/Socket.tsx
  server/package-lock.json
  server/src/app.ts
  server/src/routes/api.ts
  server/src/routes/oauth.ts
  server/src/service/interface.ts
  server/src/sockets/socketIO.ts
Labels: Frontend 🖥, Backend 💾

#67 [Day9] 그룹 리스트 검색 로직 구현
  .github/PULL_REQUEST_TEMPLATE.md
  client/src/components/LoginPage/Footer.tsx
  client/src/components/common/GroupSideBar.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/SideBar.tsx
  client/src/index.tsx
  client/src/utils/types.tsx
  server/src/routes/oauth.ts
  server/src/service/dbManager.ts
  server/tsconfig.json
Labels: Frontend 🖥

#66 [Day09] 사용자 검색 API 제작 및 로컬 DB 테스트 + UI 개선
  client/src/api/fetch.ts
  client/src/components/common/Gnb.tsx
  client/src/components/common/UserCard.tsx
  client/src/components/common/UserSearch.tsx
  client/src/utils/types.tsx
  server/src/routes/api.ts
  server/src/service/dbManager.ts
Labels: Frontend 🖥, Backend 💾

#69 [Day09] Main PR
  .github/PULL_REQUEST_TEMPLATE.md
  client/src/api/fetch.ts
  client/src/components/LoginPage/Footer.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/SideBar.tsx
  client/src/components/common/Socket.tsx
  client/src/components/common/UserCard.tsx
  client/src/components/common/UserSearch.tsx
  client/src/index.tsx
  client/src/utils/types.tsx
  server/package-lock.json
  server/src/app.ts
  server/src/routes/api.ts
  server/src/routes/oauth.ts
  server/src/service/dbManager.ts
  server/src/service/interface.ts
  server/src/sockets/socketIO.ts
  server/tsconfig.json
Labels: Main PR 👾

#82 [Day11] 1:1 채팅 UI 구성 (CSS) 및 로직 재수정
  README.md
  client/package-lock.json
  client/src/api/fetch.ts
  client/src/components/common/AlarmSideBar.tsx
  client/src/components/common/AlertSideBar.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar.tsx
  client/src/components/common/SelectorSideBar.tsx
  client/src/components/index.tsx
  client/src/pages/HomePage.tsx
  client/src/recoil/modal.ts
  client/src/utils/types.tsx
  server/package-lock.json
  server/src/routes/api.ts
  server/src/service/dbManager.ts
Labels: Frontend 🖥, Backend 💾

#80 [Day11] 로그아웃, recoil, 채팅 및 Router, url 시도
  client/src/Router.tsx
  client/src/api/fetch.ts
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/common/Authority.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/Socket.tsx
  client/src/components/index.tsx
  client/src/pages/GroupPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/recoil/modal.ts
  server/src/routes/api.ts
  server/src/sockets/socketIO.ts
Labels: Frontend 🖥, Backend 💾

#81 [Day11] 게시글 박스 UI 구현 및 로컬 DB 연동 테스트
  client/src/api/fetch.ts
  client/src/components/HomePage/Post.tsx
  client/src/components/HomePage/PostImageBox.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/UserSearch.tsx
  client/src/images/gnb-mypage.svg
  client/src/images/icon-comment.svg
  client/src/images/icon-like-badge.svg
  client/src/images/icon-like.svg
  client/src/images/icon-private.svg
  client/src/images/icon-public.svg
  client/src/images/index.tsx
  client/src/mock/index.tsx
  client/src/pages/HomePage.tsx
  client/src/utils/textUtil.ts
  client/src/utils/types.tsx
  server/src/routes/api.ts
  server/src/service/dbManager.ts
Labels: Frontend 🖥, Backend 💾

#83 [Day12] Main PR
  README.md
  client/package-lock.json
  client/src/Router.tsx
  client/src/api/fetch.ts
  client/src/components/HomePage/Post.tsx
  client/src/components/HomePage/PostImageBox.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal.tsx
  client/src/components/HomePage/index.tsx
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/LoginPage/index.tsx
  client/src/components/common/AlarmSideBar.tsx
  client/src/components/common/AlertSideBar.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/SelectorSideBar.tsx
  client/src/components/common/SideBar.tsx
  client/src/components/common/Socket.tsx
  client/src/components/common/UserCard.tsx
  client/src/components/common/UserSearch.tsx
  client/src/components/common/index.tsx
  client/src/components/index.tsx
  client/src/images/gnb-mypage.svg
  client/src/images/icon-comment.svg
  client/src/images/icon-like-badge.svg
  client/src/images/icon-like.svg
  client/src/images/icon-photo.svg
  client/src/images/icon-private.svg
  client/src/images/icon-public.svg
  client/src/images/index.tsx
  client/src/index.css
  client/src/pages/GroupPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/pages/index.tsx
  client/src/recoil/modal.ts
  client/src/recoil/store.ts
  client/src/theme/palette.ts
  client/src/utils/textUtil.ts
  client/src/utils/types.tsx
  server/package-lock.json
  server/src/routes/api.ts
  server/src/service/dbManager.ts
  server/src/sockets/socketIO.ts
Labels: Main PR 👾

#84 [Day12] 1대1 채팅완성, 내일 머지 전 공유
  client/package-lock.json
  client/src/components/common/ChatSideBar.tsx
  server/package-lock.json
  server/src/models/tables/Chat.ts
  server/src/models/tables/User.ts
  server/src/service/dbManager.ts
  server/src/sockets/socketIO.ts
Labels: Frontend 🖥, Backend 💾, Setting 🛠

#86 [Day12] 게시글 작성 모달창 UI 구현
  client/src/components/HomePage/Post.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal.tsx
  client/src/components/HomePage/PostWriterModal/AddContentsBar.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/ModalContents.tsx
  client/src/components/HomePage/PostWriterModal/ModalTitle.tsx
  client/src/components/HomePage/PostWriterModal/PostInfo.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/HomePage/index.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/UserSearch.tsx
  client/src/images/icons/gnb-alarm.svg
  client/src/images/icons/gnb-down-arrow.svg
  client/src/images/icons/gnb-group-active.svg
  client/src/images/icons/gnb-group.svg
  client/src/images/icons/gnb-home-active.svg
  client/src/images/icons/gnb-home.svg
  client/src/images/icons/gnb-message.svg
  client/src/images/icons/icon-comment.svg
  client/src/images/icons/icon-like-badge.svg
  client/src/images/icons/icon-like.svg
  client/src/images/icons/icon-photo.svg
  client/src/images/icons/icon-private.svg
  client/src/images/icons/icon-public.svg
  client/src/images/icons/icon-search.svg
  client/src/images/icons/index.tsx
  client/src/images/index.tsx
  client/src/images/profile-default.png
  client/src/index.css
  client/src/pages/HomePage.tsx
  client/src/recoil/store.ts
  client/src/theme/palette.ts
  client/src/utils/types.tsx
Labels: Frontend 🖥

#87 [Day12] 1대1 채팅, DB 수정, URL 접근 막기 시도
  client/package-lock.json
  client/src/Router.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/InitUserData.tsx
  server/package-lock.json
  server/src/models/tables/Chat.ts
  server/src/models/tables/User.ts
  server/src/routes/api.ts
  server/src/service/dbManager.ts
  server/src/sockets/socketIO.ts
Labels: Frontend 🖥, Backend 💾

#88 [Day12] 게시글 박스 여러개의 이미지 보이도록 설정, 이미지 뷰어 제작 및 코드 정리
  client/src/components/HomePage/ImageViewer.tsx
  client/src/components/HomePage/Post.tsx
  client/src/components/HomePage/PostImageBox.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/index.tsx
  client/src/components/common/UserSearch.tsx
  client/src/images/error-image.png
  client/src/images/index.tsx
  client/src/pages/HomePage.tsx
  client/src/recoil/store.ts
  client/src/utils/imageUtil.ts
  client/src/utils/types.tsx
Labels: Frontend 🖥

#89 [Day13] Main PR
  client/package-lock.json
  client/src/Router.tsx
  client/src/components/HomePage/ImageViewer.tsx
  client/src/components/HomePage/Post.tsx
  client/src/components/HomePage/PostImageBox.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal.tsx
  client/src/components/HomePage/PostWriterModal/AddContentsBar.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/ModalContents.tsx
  client/src/components/HomePage/PostWriterModal/ModalTitle.tsx
  client/src/components/HomePage/PostWriterModal/PostInfo.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/HomePage/index.tsx
  client/src/components/LoginPage/Greeter.tsx
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/UserSearch.tsx
  client/src/images/error-image.png
  client/src/images/icons/gnb-alarm.svg
  client/src/images/icons/gnb-down-arrow.svg
  client/src/images/icons/gnb-group-active.svg
  client/src/images/icons/gnb-group.svg
  client/src/images/icons/gnb-home-active.svg
  client/src/images/icons/gnb-home.svg
  client/src/images/icons/gnb-message.svg
  client/src/images/icons/icon-comment.svg
  client/src/images/icons/icon-like-badge.svg
  client/src/images/icons/icon-like.svg
  client/src/images/icons/icon-photo.svg
  client/src/images/icons/icon-private.svg
  client/src/images/icons/icon-public.svg
  client/src/images/icons/icon-search.svg
  client/src/images/icons/index.tsx
  client/src/images/index.tsx
  client/src/images/profile-default.png
  client/src/index.css
  client/src/pages/HomePage.tsx
  client/src/recoil/store.ts
  client/src/theme/palette.ts
  client/src/utils/imageUtil.ts
  client/src/utils/types.tsx
  server/package-lock.json
  server/src/models/tables/Chat.ts
  server/src/models/tables/User.ts
  server/src/routes/api.ts
  server/src/service/dbManager.ts
  server/src/sockets/socketIO.ts
Labels: Main PR 👾

#90 [Day13] 게시글 추가 API 작성 및 게시글 공개범위, 글자 수 제한 구현
  client/src/api/fetch.ts
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/ModalContents.tsx
  client/src/components/HomePage/PostWriterModal/ModalTitle.tsx
  client/src/components/HomePage/PostWriterModal/PostInfo.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/UserCard.tsx
  client/src/components/common/UserSearch.tsx
  client/src/pages/HomePage.tsx
  client/src/recoil/store.ts
  client/src/theme/palette.ts
  client/src/utils/textUtil.ts
  client/src/utils/types.tsx
  server/src/models/index.ts
  server/src/routes/api.ts
  server/src/service/dbManager.ts
  server/src/service/interface.ts
Labels: Frontend 🖥, Backend 💾

#91 [Day13] ChatSiderBar, CurrentUser, LoginPage 리팩토링 & 자잘한 작업
  client/src/components/LoginPage/Footer.tsx
  client/src/components/LoginPage/Greeter.tsx
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/components/common/Gnb.tsx
  client/src/images/icons/gnb-alarm-active.svg
  client/src/images/icons/gnb-down-arrow-active.svg
  client/src/images/icons/gnb-message-active.svg
  client/src/images/icons/icon-photo.svg
  client/src/images/icons/icon-submit.svg
  client/src/images/icons/index.tsx
Labels: Frontend 🖥

#92 [Day13] 멘토님 의견 반영, url 진입 막기, 오브젝트 스토리지
  client/src/Router.tsx
  client/src/api/fetch.ts
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/InitUserData.tsx
  client/src/pages/IsLoginPage.tsx
  client/src/pages/index.tsx
  client/src/recoil/store.ts
  server/package-lock.json
  server/package.json
  server/src/service/objectStorage.ts
  server/src/sockets/socketIO.ts
Labels: Frontend 🖥, Backend 💾

#93 [Day13] 게시글 무한스크롤, 스켈레톤 디자인 및 게시글 조회 로직 변경 외
  client/src/Router.tsx
  client/src/api/fetch.ts
  client/src/components/HomePage/Post.tsx
  client/src/components/HomePage/Post/Body.tsx
  client/src/components/HomePage/Post/Footer.tsx
  client/src/components/HomePage/Post/Header.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/Skeleton/FakeBody.tsx
  client/src/components/HomePage/Skeleton/FakeHeader.tsx
  client/src/components/HomePage/Skeleton/index.tsx
  client/src/components/HomePage/index.tsx
  client/src/recoil/store.ts
  client/src/theme/palette.ts
  client/src/utils/types.tsx
  server/src/routes/api.ts
  server/src/service/dbManager.ts
Labels: Frontend 🖥, Backend 💾

#94 [Day14] Main PR
  client/package.json
  client/public/index.html
  client/src/Router.tsx
  client/src/api/fetch.ts
  client/src/components/HomePage/Post.tsx
  client/src/components/HomePage/Post/Body.tsx
  client/src/components/HomePage/Post/Footer.tsx
  client/src/components/HomePage/Post/Header.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/ModalContents.tsx
  client/src/components/HomePage/PostWriterModal/ModalTitle.tsx
  client/src/components/HomePage/PostWriterModal/PostInfo.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/HomePage/Skeleton/FakeBody.tsx
  client/src/components/HomePage/Skeleton/FakeHeader.tsx
  client/src/components/HomePage/Skeleton/index.tsx
  client/src/components/HomePage/index.tsx
  client/src/components/LoginPage/Footer.tsx
  client/src/components/LoginPage/Greeter.tsx
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/UserCard.tsx
  client/src/components/common/UserSearch.tsx
  client/src/images/icons/gnb-alarm-active.svg
  client/src/images/icons/gnb-down-arrow-active.svg
  client/src/images/icons/gnb-message-active.svg
  client/src/images/icons/icon-photo.svg
  client/src/images/icons/icon-submit.svg
  client/src/images/icons/index.tsx
  client/src/index.css
  client/src/pages/HomePage.tsx
  client/src/pages/IsLoginPage.tsx
  client/src/pages/index.tsx
  client/src/recoil/store.ts
  client/src/theme/palette.ts
  client/src/utils/textUtil.ts
  client/src/utils/types.tsx
  server/package-lock.json
  server/package.json
  server/src/models/index.ts
  server/src/routes/api.ts
  server/src/service/dbManager.ts
  server/src/service/interface.ts
  server/src/service/objectStorage.ts
  server/src/sockets/socketIO.ts
Labels: Main PR 👾

#95 [Day14] 게시글 댓글 작성 기능 구현
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/HomePage/Post/Footer.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/pages/IsLoginPage.tsx
  client/src/recoil/store.ts
  client/src/utils/types.tsx
  server/src/service/dbManager.ts
  server/src/service/interface.ts
  server/src/sockets/socketIO.ts
Labels: Frontend 🖥, Backend 💾

#96 [Day14] 게시글 삭제 기능
  client/src/api/fetch.ts
  client/src/components/HomePage/Post/Body.tsx
  client/src/components/HomePage/Post/Footer.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/recoil/store.ts
  client/src/utils/textUtil.ts
  client/src/utils/types.tsx
  server/src/routes/api.ts
  server/src/service/dbManager.ts
  server/src/service/interface.ts
Labels: Frontend 🖥, Backend 💾

#97 [Day14] 게시글 REST API 구현 및 좋아요 이벤트 일부 구현
  .vscode/settings.json
  client/src/api/fetch.ts
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/images/icons/icon-like-active.svg
  client/src/images/icons/index.tsx
  client/src/utils/types.tsx
  server/src/routes/api.ts
  server/src/service/dbManager.ts
Labels: Frontend 🖥, Backend 💾

#99 [Day14] Main PR
  .vscode/settings.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/Router.tsx
  client/src/api/fetch.ts
  client/src/components/HomePage/Post/Body.tsx
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/HomePage/Post/Footer.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/images/icons/icon-like-active.svg
  client/src/images/icons/index.tsx
  client/src/pages/IsLoginPage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/recoil/store.ts
  client/src/utils/textUtil.ts
  client/src/utils/types.tsx
  server/src/app.ts
  server/src/routes/api.ts
  server/src/service/dbManager.ts
  server/src/service/interface.ts
  server/src/service/objectStorage.ts
  server/src/sockets/socketIO.ts
Labels: Main PR 👾

#101 [Week2] 게시물 수정 작업 추가 및 충돌 해결
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal/AddContentsBar.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/ModalContents.tsx
  client/src/components/HomePage/PostWriterModal/ModalTitle.tsx
  client/src/components/HomePage/PostWriterModal/PostInfo.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/UserSearch.tsx
  client/src/hooks/useClosePostModal.tsx
  client/src/recoil/store.ts
  client/src/types/post/index.tsx
  server/src/routes/api.ts
Labels: Frontend 🖥, Backend 💾

#106 [Day16] 소켓 수정 시도 및 이미지 업로드 구현 등
  client/src/Router.tsx
  client/src/api/fetch.ts
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal/AddContentsBar.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/ModalContents.tsx
  client/src/components/HomePage/PostWriterModal/ModalTitle.tsx
  client/src/components/HomePage/PostWriterModal/PostInfo.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/common/AlarmSideBar.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/InitSocket.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/SelectorSideBar.tsx
  client/src/components/common/UserSearch.tsx
  client/src/components/common/index.tsx
  client/src/hooks/useClosePostModal.tsx
  client/src/pages/GroupPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/IsLoginPage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/recoil/store.ts
  client/src/types/post/index.tsx
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/models/tables/Alarm.ts
  server/src/models/tables/Chat.ts
  server/src/models/tables/Comment.ts
  server/src/models/tables/Group.ts
  server/src/models/tables/GroupChat.ts
  server/src/models/tables/Like.ts
  server/src/models/tables/Post.ts
  server/src/models/tables/Problem.ts
  server/src/models/tables/User.ts
  server/src/models/tables/UserGroup.ts
  server/src/models/tables/UserProblem.ts
  server/src/routes/api.ts
  server/src/routes/oauth.ts
  server/src/service/dbManager.ts
  server/src/service/objectStorage.ts
  server/src/sockets/socketIO.ts
  server/src/types/interface.ts
Labels: Frontend 🖥, Backend 💾, Bug :bug:

#103 [Day16] ChatSideBar 리팩토링
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/theme/style.tsx
  client/src/types/message/index.tsx
  server/src/service/dbManager.ts
Labels: Frontend 🖥

#107 [Day16] 좋아요 DB 연동 및 그룹별 페이지 Layout 일부 구현
  client/src/api/fetch.ts
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal/AddContentsBar.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/ModalTitle.tsx
  client/src/components/HomePage/PostWriterModal/PostInfo.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/images/groupimg/index.tsx
  client/src/images/groupimg/os.jpg
  client/src/index.css
  client/src/pages/GroupPage.tsx
  client/src/pages/HomePage.tsx
  client/src/theme/palette.tsx
  client/src/types/post/index.tsx
  package-lock.json
  server/src/models/tables/Like.ts
  server/src/routes/api.ts
  server/src/service/dbManager.ts
Labels: Frontend 🖥, Backend 💾

#111 [Day17] 이미지 업로드 보완, 미리보기 및 취소
  client/src/components/HomePage/ImageViewer/index.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/hooks/useClosePostModal.tsx
  client/src/recoil/store.ts
  server/src/service/date.ts
  server/src/service/dbManager/index.ts
  server/src/service/objectStorage.ts
  server/src/sockets/socketIO.ts
Labels: Frontend 🖥, Bug :bug:, Question :question:

#109 [Day17] 게시물 댓글 로직 변경 & 유저 접속중 여부 구현중
  client/package-lock.json
  client/src/api/fetch.ts
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/LoginPage/Footer.tsx
  client/src/components/LoginPage/Greeter.tsx
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/theme/style.tsx
  client/src/types/comment/index.tsx
  server/package-lock.json
  server/src/routes/api.ts
  server/src/service/dbManager/comment.ts
  server/src/service/dbManager/index.ts
  server/src/service/dbManager/user.ts
  server/src/sockets/socketIO.ts
  server/src/types/interface.ts
Labels: Frontend 🖥, Backend 💾

#112 [Day17] 그룹별 페이지 NavBar UI 구현 및 로딩, 경고모달창 구현
  client/src/api/fetch.ts
  client/src/components/GroupPage/GroupNavBar/GroupNavMiddle.tsx
  client/src/components/GroupPage/GroupNavBar/GroupNavTitle.tsx
  client/src/components/GroupPage/GroupNavBar/GroupNavigation.tsx
  client/src/components/GroupPage/GroupNavBar/index.tsx
  client/src/components/GroupPage/index.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/common/AlertModal.tsx
  client/src/components/common/UserSearch.tsx
  client/src/components/common/index.tsx
  client/src/hooks/useAlertModal.tsx
  client/src/images/main-logo.png
  client/src/pages/GroupPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/IsLoginPage.tsx
  client/src/recoil/store.ts
  client/src/theme/style.tsx
  client/src/types/common/index.tsx
  server/src/routes/api.ts
  server/src/service/dbManager/index.ts
  server/src/service/dbManager/like.ts
  server/src/service/dbManager/post.ts
  server/src/sockets/socketIO.ts
  server/tsconfig.json
Labels: Frontend 🖥

#113 [Day18] Main PR
  client/src/App.tsx
  client/src/api/fetch.ts
  client/src/components/GroupPage/Problem/index.tsx
  client/src/components/GroupPage/ProblemList/index.tsx
  client/src/components/GroupPage/index.tsx
  client/src/components/HomePage/ImageViewer/index.tsx
  client/src/components/HomePage/Post/Body.tsx
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/PostImageBox/index.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/LoginPage/Footer.tsx
  client/src/components/LoginPage/Greeter.tsx
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/common/AlertModal.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/UserSearch.tsx
  client/src/hooks/useClosePostModal.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/pages/GroupPage.tsx
  client/src/pages/HomePage.tsx
  client/src/recoil/store.ts
  client/src/types/comment/index.tsx
  client/src/types/group/index.tsx
  server/src/models/tables/User.ts
  server/src/models/tables/UserProblem.ts
  server/src/routes/api.ts
  server/src/service/date.ts
  server/src/service/dbManager/comment.ts
  server/src/service/dbManager/index.ts
  server/src/service/dbManager/problem.ts
  server/src/service/dbManager/search.ts
  server/src/service/dbManager/user.ts
  server/src/service/objectStorage.ts
  server/src/sockets/socketIO.ts
  server/src/types/interface.ts
Labels: Main PR 👾

#117 [Day18] 유저 현재접속 여부 구현 & 채팅 전송 hover
  client/package-lock.json
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/images/icons/icon-submit-active.svg
  client/src/images/icons/icon-submit.svg
  client/src/images/icons/index.tsx
  client/src/types/common/index.tsx
  server/package-lock.json
  server/package.json
  server/src/routes/api.ts
  server/src/routes/oauth.ts
  server/src/service/dbManager/chat.ts
  server/src/service/dbManager/comment.ts
  server/src/service/dbManager/index.ts
  server/src/service/dbManager/user.ts
  server/src/sockets/socketIO.ts
  server/src/types/interface.ts
Labels: Frontend 🖥, Backend 💾

#119 [Day18] 가입된 그룹의 문제를 홈 화면에서 조회하도록 구현 및 성취도 로직 변경 등
  client/src/api/fetch.ts
  client/src/components/GroupPage/Problem/index.tsx
  client/src/components/GroupPage/ProblemList/index.tsx
  client/src/components/HomePage/ImageViewer/index.tsx
  client/src/components/HomePage/Post/Footer.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/index.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/Skeleton/FakeAnswerWrap.tsx
  client/src/components/common/Skeleton/FakeBody.tsx
  client/src/components/common/Skeleton/FakeHeader.tsx
  client/src/components/common/Skeleton/index.tsx
  client/src/components/common/UserSearch.tsx
  client/src/components/common/index.tsx
  client/src/types/problem/index.tsx
  client/src/utils/arrayUtil.ts
  server/src/routes/api.ts
  server/src/service/dbManager/index.ts
  server/src/service/dbManager/problem.ts
  server/src/service/dbManager/user.ts
Labels: Frontend 🖥, Backend 💾

#123 [Day19] 이미지 업로드 완료, 세션 주기 추가 등
  client/src/Router.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/common/AlertModal.tsx
  client/src/hooks/useClosePostModal.tsx
  client/src/recoil/store.ts
  server/src/app.ts
Labels: Frontend 🖥, Backend 💾

#125 [Day19] 정답률 로직 처리, 가입 그룹별 문제 조회, 새로운 게시글 알림 추가
  client/src/api/fetch.ts
  client/src/components/GroupPage/Problem/index.tsx
  client/src/components/GroupPage/ProblemList/index.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/NewPostAlert/Alert.tsx
  client/src/components/common/NewPostAlert/index.tsx
  client/src/components/common/index.tsx
  client/src/pages/GroupPage.tsx
  client/src/recoil/store.ts
  client/src/types/user/index.tsx
  server/src/service/dbManager/user.ts
  server/src/sockets/socketIO.ts
Labels: Frontend 🖥, Backend 💾

#124 [Day19] 그룹 가입 구현, 그룹 사이드바 연동 구현, 로딩 모달창 구현
  client/src/api/fetch.ts
  client/src/components/GroupPage/GroupNavBar/GroupNavMiddle.tsx
  client/src/components/GroupPage/InitGroupData/index.tsx
  client/src/components/GroupSelectPage/GroupSelectList/GroupCard.tsx
  client/src/components/GroupSelectPage/GroupSelectList/index.tsx
  client/src/components/common/AlertModal.tsx
  client/src/components/common/GroupSideBar/JoinedGroupCard.tsx
  client/src/components/common/GroupSideBar/index.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/LoadingModal.tsx
  client/src/components/common/index.tsx
  client/src/images/groupimg/default-group.jpg
  client/src/images/groupimg/index.tsx
  client/src/pages/GroupPage.tsx
  server/src/models/tables/UserGroup.ts
  server/src/routes/api.ts
  server/src/service/dbManager/group.ts
  server/src/service/dbManager/index.ts
Labels: Frontend 🖥, Backend 💾

#150 [주말] 버그 수정
  .github/workflows/main.yml
  README.md
  client/public/index.html
  client/src/App.tsx
  client/src/components/GroupPage/Problem/index.tsx
  client/src/components/GroupPage/ProblemList/index.tsx
  client/src/components/HomePage/ImageViewer/index.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/InitUserData.tsx
  client/src/images/grid.png
  client/src/images/index.tsx
  client/src/index.css
  client/src/recoil/store.ts
  client/src/theme/SpoqaHanSansNeo-Regular.otf
  client/src/types/problem/index.tsx
  client/src/types/user/index.tsx
  server/src/service/dbManager/comment.ts
Labels: Frontend 🖥

#149 [주말] 프로필 페이지 UI 구현 및 반응형 레이아웃 구현
  client/public/index.html
  client/src/Router.tsx
  client/src/components/GroupPage/GroupChat/index.tsx
  client/src/components/GroupPage/GroupNavBar/index.tsx
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/HomePage/Post/Header.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal/PostInfo.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/ProfilePage/InitProfileData/index.tsx
  client/src/components/ProfilePage/ProfileBar/ProfileEdit.tsx
  client/src/components/ProfilePage/ProfileBar/ProfileInfo.tsx
  client/src/components/ProfilePage/ProfileBar/ProfilePhoto.tsx
  client/src/components/ProfilePage/ProfileBar/index.tsx
  client/src/components/ProfilePage/ProfileCover/index.tsx
  client/src/components/ProfilePage/index.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar/JoinedGroupCard.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/SideBar.tsx
  client/src/hooks/useResetGroup.tsx
  client/src/images/index.tsx
  client/src/pages/GroupPage.tsx
  client/src/pages/GroupSelectPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/recoil/store.ts
  client/src/types/common/index.tsx
  client/src/types/user/index.tsx
Labels: Frontend 🖥

#151 [Day21] Main PR
  client/public/index.html
  client/src/Router.tsx
  client/src/api/fetch.ts
  client/src/components/GroupPage/GroupChat/index.tsx
  client/src/components/GroupPage/GroupNavBar/index.tsx
  client/src/components/GroupPage/Problem/index.tsx
  client/src/components/GroupPage/ProblemList/index.tsx
  client/src/components/GroupSelectPage/GroupSelectList/index.tsx
  client/src/components/HomePage/ImageViewer/index.tsx
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/HomePage/Post/Footer.tsx
  client/src/components/HomePage/Post/Header.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal/PostInfo.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/ProfilePage/InitProfileData/index.tsx
  client/src/components/ProfilePage/ProfileBar/ProfileEdit.tsx
  client/src/components/ProfilePage/ProfileBar/ProfileInfo.tsx
  client/src/components/ProfilePage/ProfileBar/ProfilePhoto.tsx
  client/src/components/ProfilePage/ProfileBar/index.tsx
  client/src/components/ProfilePage/ProfileCover/index.tsx
  client/src/components/ProfilePage/index.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar/JoinedGroupCard.tsx
  client/src/components/common/GroupSideBar/index.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/SideBar.tsx
  client/src/hooks/useResetGroup.tsx
  client/src/images/grid.png
  client/src/images/icons/gnb-group.svg
  client/src/images/index.tsx
  client/src/pages/GroupPage.tsx
  client/src/pages/GroupSelectPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/recoil/store.ts
  client/src/types/common/index.tsx
  client/src/types/post/index.tsx
  client/src/types/problem/index.tsx
  client/src/types/user/index.tsx
  server/src/service/dbManager/comment.ts
  server/src/service/dbManager/index.ts
  server/src/sockets/socketIO.ts
Labels: Main PR 👾

#156 [Day21] CommentNum 추가, 댓글수 호출 로직 변경, 버그 수정
  client/src/components/GroupPage/GroupChat/index.tsx
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/HomePage/Post/Footer.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/UserCard.tsx
  client/src/images/icons/gnb-logout.svg
  client/src/images/icons/index.tsx
  client/src/pages/GroupPage.tsx
  client/src/recoil/store.ts
  client/src/types/post/index.tsx
  server/src/models/tables/Post.ts
  server/src/service/dbManager/comment.ts
  server/src/sockets/socketIO.ts
  server/src/types/interface.ts
Labels: Frontend 🖥, Backend 💾

#155 [Day21] 게시글 새로고침 및 프로필 게시글 확인 기능
  client/src/api/fetch.ts
  client/src/components/HomePage/Post/Footer.tsx
  client/src/components/HomePage/Post/Header.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/ProfilePage/PostList/index.tsx
  client/src/components/ProfilePage/index.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/NewPostAlert/Alert.tsx
  client/src/components/common/NewPostAlert/index.tsx
  client/src/components/common/UserCard.tsx
  client/src/components/common/UserSearch.tsx
  client/src/pages/ProfilePage.tsx
  server/src/routes/api.ts
  server/src/service/dbManager/post.ts
Labels: Frontend 🖥, Backend 💾

#154 [Day21] 프로필 커버 이미지 및 업로드 용량 제한 등
  .vscode/settings.json
  README.md
  client/src/api/fetch.ts
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/ProfilePage/ProfileBar/ProfileInfo.tsx
  client/src/components/ProfilePage/ProfileBar/index.tsx
  client/src/components/ProfilePage/ProfileCover/index.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/pages/ProfilePage.tsx
  server/src/app.ts
  server/src/routes/api.ts
  server/src/service/dbManager/index.ts
  server/src/service/dbManager/user.ts
  server/src/service/objectStorage.ts
  server/src/types/interface.ts
Labels: Frontend 🖥, Backend 💾

#153 [Day21] 프로필 페이지 렌더링, 프로필 수정 기능 추가, 내 프로필 페이지 기능 추가
  client/src/api/fetch.ts
  client/src/components/GroupPage/GroupNavBar/GroupNavTitle.tsx
  client/src/components/GroupSelectPage/GroupSelectList/GroupCard.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/ProfilePage/InitProfileData/index.tsx
  client/src/components/ProfilePage/PostList/index.tsx
  client/src/components/ProfilePage/ProfileBar/ProfileEdit.tsx
  client/src/components/ProfilePage/ProfileBar/ProfileInfo.tsx
  client/src/components/ProfilePage/ProfileBar/ProfilePhoto.tsx
  client/src/components/ProfilePage/ProfileBar/index.tsx
  client/src/components/ProfilePage/ProfileCover/index.tsx
  client/src/components/ProfilePage/ProfileEditModal/index.tsx
  client/src/components/ProfilePage/index.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar/JoinedGroupCard.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/SideBar.tsx
  client/src/components/common/UserCard.tsx
  client/src/hooks/useResetProfile.tsx
  client/src/pages/GroupPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/recoil/store.ts
  client/src/types/common/index.tsx
  client/src/types/user/index.tsx
  server/src/routes/api.ts
  server/src/service/dbManager/index.ts
  server/src/service/dbManager/user.ts
  server/src/types/interface.ts
Labels: Frontend 🖥, Backend 💾

#157 [Day22] Main PR
  .vscode/settings.json
  README.md
  client/src/api/fetch.ts
  client/src/components/GroupPage/GroupChat/index.tsx
  client/src/components/GroupPage/GroupNavBar/GroupNavTitle.tsx
  client/src/components/GroupSelectPage/GroupSelectList/GroupCard.tsx
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/HomePage/Post/Footer.tsx
  client/src/components/HomePage/Post/Header.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/ProfilePage/InitProfileData/index.tsx
  client/src/components/ProfilePage/PostList/index.tsx
  client/src/components/ProfilePage/ProfileBar/ProfileEdit.tsx
  client/src/components/ProfilePage/ProfileBar/ProfileInfo.tsx
  client/src/components/ProfilePage/ProfileBar/ProfilePhoto.tsx
  client/src/components/ProfilePage/ProfileBar/index.tsx
  client/src/components/ProfilePage/ProfileCover/index.tsx
  client/src/components/ProfilePage/ProfileEditModal/index.tsx
  client/src/components/ProfilePage/index.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar/JoinedGroupCard.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/NewPostAlert/Alert.tsx
  client/src/components/common/NewPostAlert/index.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/SideBar.tsx
  client/src/components/common/UserCard.tsx
  client/src/components/common/UserSearch.tsx
  client/src/hooks/useResetProfile.tsx
  client/src/images/icons/gnb-logout.svg
  client/src/images/icons/index.tsx
  client/src/pages/GroupPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/recoil/store.ts
  client/src/types/common/index.tsx
  client/src/types/post/index.tsx
  client/src/types/user/index.tsx
  server/src/app.ts
  server/src/models/tables/Post.ts
  server/src/routes/api.ts
  server/src/service/dbManager/comment.ts
  server/src/service/dbManager/index.ts
  server/src/service/dbManager/post.ts
  server/src/service/dbManager/user.ts
  server/src/service/objectStorage.ts
  server/src/sockets/socketIO.ts
  server/src/types/interface.ts
Labels: Main PR 👾

#159 [Day22] 알림 기능 구현 ( 1:1 채팅, 게시물 댓글 ) & 버그 수정
  client/src/Router.tsx
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/common/AlarmSideBar.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/Gnb.tsx
  client/src/pages/ProfilePage.tsx
  client/src/recoil/store.ts
  server/src/models/tables/Alarm.ts
  server/src/service/dbManager/alarm.ts
  server/src/service/dbManager/index.ts
  server/src/sockets/socketIO.ts
Labels: Frontend 🖥, Backend 💾

#160 [Day22] 프로필 페이지 이미지 크기 설정 및 AbortController 적용
  client/src/api/fetch.ts
  client/src/components/GroupPage/GroupChat/index.tsx
  client/src/components/HomePage/Post/Body.tsx
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/HomePage/Post/Header.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostImageBox/ActiveImageBox.tsx
  client/src/components/HomePage/PostImageBox/OneImage.tsx
  client/src/components/HomePage/PostImageBox/ThreeImages.tsx
  client/src/components/HomePage/PostImageBox/TwoImages.tsx
  client/src/components/HomePage/PostImageBox/index.tsx
  client/src/components/HomePage/PostImageBox/styles.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/ProfilePage/PostList/index.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/Skeleton/index.tsx
  client/src/components/common/UserCard.tsx
  client/src/components/common/index.tsx
  client/src/pages/HomePage.tsx
  client/src/types/post/index.tsx
Labels: Frontend 🖥

#163 [Day22] 프로필 커버 이미지 편집 수정 및 그룹, 문제 생성 등
  client/src/api/fetch.ts
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/ProfilePage/InitProfileData/index.tsx
  client/src/components/ProfilePage/ProfileCover/index.tsx
  client/src/pages/ProfilePage.tsx
  server/src/models/tables/Problem.ts
  server/src/service/dbManager/index.ts
Labels: Frontend 🖥, Backend 💾, Setting 🛠

#161 [Day22] 프로필 페이지 문제 정답률 구현 및 자잘한 버그 수정
  client/src/api/fetch.ts
  client/src/components/HomePage/Post/Header.tsx
  client/src/components/HomePage/Post/index.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal/PostInfo.tsx
  client/src/components/ProfilePage/ProfileBar/ProfileEdit.tsx
  client/src/components/ProfilePage/ProfileBar/ProfilePhoto.tsx
  client/src/components/ProfilePage/ProfileEditModal/index.tsx
  client/src/components/ProfilePage/ProfileInfoBar/index.tsx
  client/src/components/ProfilePage/index.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/LoadingModal.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/UserSearch.tsx
  client/src/hooks/useResetProfile.tsx
  client/src/pages/GroupPage.tsx
  client/src/pages/GroupSelectPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/types/user/index.tsx
  server/src/routes/api.ts
  server/src/service/dbManager/index.ts
  server/src/service/dbManager/problem.ts
  server/src/service/dbManager/user.ts
Labels: Frontend 🖥, Backend 💾

#171 [Day23] 알림 소리기능 구현 및 오류 수정
  client/public/images/algorithm.png
  client/public/images/database.jpg
  client/public/images/javascript.png
  client/src/audio.d.ts
  client/src/components/GroupPage/GroupChat/index.tsx
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/common/AlarmSideBar.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/sounds/comment-notify.mp3
  client/src/sounds/message-notify.mp3
  server/src/sockets/socketIO.ts
Labels: Frontend 🖥, Backend 💾

#173 [Day23] 이미지 업로드 용량 제한 및 자료구조, 백엔드 추가 등
  .github/workflows/main.yml
  client/public/images/be.jpg
  client/public/images/ds.jpg
  client/public/images/os.jpg
  client/src/App.tsx
  client/src/Router.tsx
  client/src/components/HomePage/Post/Header.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/HomePage/PostImageBox/OneImage.tsx
  client/src/components/HomePage/PostImageBox/TwoImages.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/ModalContents.tsx
  client/src/components/HomePage/PostWriterModal/ModalTitle.tsx
  client/src/components/HomePage/PostWriterModal/index.tsx
  client/src/components/LoginPage/Greeter.tsx
  client/src/components/LoginPage/LoginBox.tsx
  client/src/components/ProfilePage/InitProfileData/index.tsx
  client/src/components/ProfilePage/PostList/index.tsx
  client/src/components/ProfilePage/ProfileBar/ProfileInfo.tsx
  client/src/components/ProfilePage/ProfileBar/ProfilePhoto.tsx
  client/src/components/ProfilePage/ProfileBar/index.tsx
  client/src/components/ProfilePage/ProfileCover/index.tsx
  client/src/components/ProfilePage/ProfileInfoBar/index.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/Socket.tsx
  client/src/hooks/useAlertModal.tsx
  client/src/hooks/useResetGroup.tsx
  client/src/hooks/useResetProfile.tsx
  client/src/index.tsx
  client/src/pages/GroupSelectPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/IsLoginPage.tsx
  client/src/pages/LoginPage.tsx
  server/src/app.ts
  server/src/models/tables/Chat.ts
  server/src/models/tables/Group.ts
  server/src/models/tables/Post.ts
  server/src/models/tables/User.ts
  server/src/routes/oauth.ts
  server/src/service/dbManager/index.ts
  server/src/service/objectStorage.ts
  server/src/sockets/socketIO.ts
Labels: Frontend 🖥, Backend 💾

#172 [Day23] 문제 해설 추가, gnb 반응형 및 기타 이슈 해결
  client/public/images/boostcamp.png
  client/public/images/git.png
  client/public/images/software.png
  client/src/components/GroupPage/Problem/Explanation.tsx
  client/src/components/GroupPage/Problem/index.tsx
  client/src/components/HomePage/Post/Body.tsx
  client/src/components/HomePage/PostImageBox/OneImage.tsx
  client/src/components/HomePage/PostImageBox/ThreeImages.tsx
  client/src/components/HomePage/PostImageBox/TwoImages.tsx
  client/src/components/HomePage/PostImageBox/index.tsx
  client/src/components/HomePage/PostList.tsx
  client/src/components/ProfilePage/PostList/index.tsx
  client/src/components/ProfilePage/ProfileInfoBar/index.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/ProfilePhoto.tsx
  client/src/components/common/Skeleton/index.tsx
  client/src/components/common/UserCard.tsx
  client/src/pages/ProfilePage.tsx
  client/src/types/problem/index.tsx
Labels: Frontend 🖥

#177 [Day24] pm2 ts-node 배포 설정 및 그룹 문제 추가 등
  .github/workflows/main.yml
  client/public/images/backend.jpg
  client/public/images/computer_architecture.jpg
  client/public/images/data_structure.jpg
  client/public/images/frontend.jpg
  client/public/images/javascript.jpeg
  client/public/images/javascript.png
  client/public/images/network.jpg
  client/public/images/operating_system.jpg
  client/public/images/software_engineering.png
  client/src/images/groupimg/index.tsx
  client/src/images/groupimg/os.jpg
  server/pm2.json
  server/src/service/dbManager/index.ts
Labels: Backend 💾, Setting 🛠

#176 [Day24] 댓글 작성 시간 구현 & 버그, 디자인 수정
  client/src/components/GroupPage/GroupChat/index.tsx
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/components/common/Gnb.tsx
  client/src/recoil/store.ts
  client/src/theme/color.tsx
  client/src/theme/style.tsx
  client/src/types/comment/index.tsx
Labels: Frontend 🖥

#178 [Day24] 문제 추가 및 다크모드 그림자 설정
  client/public/images/software_engineering.png
  client/src/components/GroupPage/GroupChat/index.tsx
  client/src/components/GroupPage/Problem/index.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/common/AlarmSideBar.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/GroupSideBar/index.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/UserSearch.tsx
  client/src/theme/color.tsx
Labels: Frontend 🖥

#179 [Day24] 그룹 리스트 스크롤 관련 css 변경, 그룹 이미지 추가
  client/public/images/computer_architecture.jpg
  client/public/images/frontend.jpg
  client/public/images/network.jpg
  client/src/components/GroupPage/GroupNavBar/GroupNavMiddle.tsx
  client/src/components/common/GroupSideBar/JoinedGroupCard.tsx
  client/src/components/common/GroupSideBar/index.tsx
  client/src/utils/textUtil.ts
Labels: Frontend 🖥

#180 [Day24] Main PR
  .github/workflows/main.yml
  client/public/images/backend.jpg
  client/public/images/computer_architecture.jpg
  client/public/images/data_structure.jpg
  client/public/images/frontend.jpg
  client/public/images/javascript.jpeg
  client/public/images/javascript.png
  client/public/images/network.jpg
  client/public/images/operating_system.jpg
  client/public/images/se.png
  client/public/images/software_engineering.png
  client/src/components/GroupPage/GroupChat/index.tsx
  client/src/components/GroupPage/GroupNavBar/GroupNavMiddle.tsx
  client/src/components/GroupPage/Problem/index.tsx
  client/src/components/HomePage/Post/Comment.tsx
  client/src/components/HomePage/Post/OptionModal.tsx
  client/src/components/common/AlarmSideBar.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/CurrentUser.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar/JoinedGroupCard.tsx
  client/src/components/common/GroupSideBar/index.tsx
  client/src/components/common/InfoSideBar.tsx
  client/src/components/common/UserSearch.tsx
  client/src/images/groupimg/index.tsx
  client/src/images/groupimg/os.jpg
  client/src/recoil/store.ts
  client/src/theme/color.tsx
  client/src/theme/style.tsx
  client/src/types/comment/index.tsx
  client/src/utils/textUtil.ts
  server/pm2.json
  server/src/service/dbManager/index.ts
Labels: Main PR 👾

#194 [Day26] 버그 해결 및 디자인 수정
  client/src/components/GroupPage/GroupChat/index.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/Gnb.tsx
  client/src/images/icons/index.tsx
Labels: Frontend 🖥

#198 [Day26] 이미지 업로드/수정 취약점 해결 등
  client/src/components/common/InitSocket.tsx
  client/src/components/common/index.tsx
  client/src/pages/GroupPage.tsx
  client/src/pages/GroupSelectPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/ProfilePage.tsx
  server/src/routes/api.ts
  server/src/service/objectStorage.ts
  server/src/service/pictureCheck.ts
Labels: Frontend 🖥, Backend 💾

#199 [Day26] 다크모드 처리
  README.md
  client/src/components/GroupPage/ProblemList/index.tsx
  client/src/components/ProfilePage/PostList/index.tsx
  client/src/components/common/GroupSideBar/index.tsx
  client/src/components/common/UserSearch.tsx
  client/src/images/icons/index.tsx
Labels: Frontend 🖥

#196 [Day26] 피드백 반영 및 공통컴포넌트 구조 변경, 웹폰트로 변경
  client/public/index.html
  client/src/App.tsx
  client/src/Router.tsx
  client/src/components/GroupPage/GroupNavBar/GroupNavTitle.tsx
  client/src/components/GroupSelectPage/GroupSelectTitle.tsx
  client/src/components/HomePage/PostImageBox/ActiveImageBox.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal/AddContentsBar.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/PostInfo.tsx
  client/src/components/ProfilePage/PostList/index.tsx
  client/src/components/common/FakeComponents/FakeGnb.tsx
  client/src/components/common/FakeComponents/FakeSideBar.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar/index.tsx
  client/src/components/common/InitTheme.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/SideBar.tsx
  client/src/components/common/UserCard.tsx
  client/src/components/common/index.tsx
  client/src/images/icons/index.tsx
  client/src/index.css
  client/src/pages/GroupPage.tsx
  client/src/pages/GroupSelectPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/IsLoginPage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/recoil/store.ts
  client/src/theme/SpoqaHanSansNeo-Regular.otf
  client/src/theme/palette.tsx
Labels: Frontend 🖥

#200 [Day27] Main PR
  client/public/index.html
  client/src/App.tsx
  client/src/Router.tsx
  client/src/components/GroupPage/GroupChat/index.tsx
  client/src/components/GroupPage/GroupNavBar/GroupNavTitle.tsx
  client/src/components/GroupPage/ProblemList/index.tsx
  client/src/components/GroupSelectPage/GroupSelectTitle.tsx
  client/src/components/HomePage/PostImageBox/ActiveImageBox.tsx
  client/src/components/HomePage/PostWriter.tsx
  client/src/components/HomePage/PostWriterModal/AddContentsBar.tsx
  client/src/components/HomePage/PostWriterModal/ImgUploadModal.tsx
  client/src/components/HomePage/PostWriterModal/PostInfo.tsx
  client/src/components/ProfilePage/PostList/index.tsx
  client/src/components/common/ChatSideBar.tsx
  client/src/components/common/FakeComponents/FakeGnb.tsx
  client/src/components/common/FakeComponents/FakeSideBar.tsx
  client/src/components/common/Gnb.tsx
  client/src/components/common/GroupSideBar/index.tsx
  client/src/components/common/InitSocket.tsx
  client/src/components/common/InitTheme.tsx
  client/src/components/common/InitUserData.tsx
  client/src/components/common/SideBar.tsx
  client/src/components/common/UserCard.tsx
  client/src/components/common/UserSearch.tsx
  client/src/components/common/index.tsx
  client/src/images/icons/index.tsx
  client/src/index.css
  client/src/pages/GroupPage.tsx
  client/src/pages/GroupSelectPage.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/IsLoginPage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/recoil/store.ts
  client/src/theme/SpoqaHanSansNeo-Regular.otf
  client/src/theme/palette.tsx
  server/src/routes/api.ts
  server/src/service/objectStorage.ts
  server/src/service/pictureCheck.ts
Labels: Main PR 👾
